Disable Cake integration test
because Cake in this version does not work with PHP 7.

Error: Cannot use 'String' as class name as it is reserved
File: /home/vcap/app/lib/Cake/Utility/String.php
Line: 25

The same issue appears with the upstream stacks.